apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  POSTGRES_USER: dXNlcg==            # base64('user')
  POSTGRES_PASSWORD: cGFzc3dvcmQ=    # base64('password')
  POSTGRES_DB: bXlkYXRhYmFzZQ==      # base64('mydatabase')
  
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=    # base64('guest')
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=    # base64('guest')
  
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9teWRhdGFiYXNl # base64('postgresql://user:password@postgres:5432/mydatabase') postgres, а не localhost (как под в кластере)
  CELERY_BROKER_URL: cHlhbXFwOi8vZ3Vlc3RAcmFiYml0bXE6NTY3Mi8v # base64('pyamqp://guest@rabbitmq:5672//') rabbitmq, а не localhost (как под в кластере)
  CELERY_RESULT_BACKEND: cnBjOi8v # base64('rpc://')