apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: my-app:latest
          imagePullPolicy: Never
          workingDir: /app
          command: ["sh", "-c", "celery -A app.tasks worker --loglevel=info --queues=huge_summarize_queue"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CELERY_RESULT_BACKEND